import RDBOM from '../models/RDBOM.js';
import Sale from '../models/Sale.js';
import { Item } from '../models/Inventory.js';
import SheetMetalPlan from '../models/SheetMetalPlan.js';
import PurchaseRequest from '../models/PurchaseRequest.js';
import { generatePurchaseRequestId } from './storeFlowService.js';
import { resolveFabricationLines } from '../controllers/purchaseRequestController.js';
import { sheetMetalGroupsFromBOM } from '../controllers/sheetMetalPlanController.js';
import { plainMaterialGroupsFromBOM, lengthFabricationGroupsFromBOM } from './bomMaterialGroupsService.js';

// Shared by both Sheet Metal and length-based fabrication shortfalls —
// resolveFabricationLines is category-agnostic (just {values, quantity}), so
// the same request-building logic works for either. Pre-approved and
// order-scoped, mirroring lowStockReorderCron.js's own auto-PR shape exactly
// so it displays/behaves identically on the existing (untouched) Material
// Handshake Purchase screens. Relies on PurchaseRequest's new partial unique
// index (storeOrderId + materialCode, autoGenerated) to make a genuine
// duplicate impossible under a concurrent double-submit — on conflict, reuse
// the already-created request's id instead of erroring.
async function raiseFabricationPurchaseRequest({ matItem, dimensionValues, piecesShort, compositeMaterialCode, order }) {
  const resolved = await resolveFabricationLines(matItem, [{ values: dimensionValues, quantity: piecesShort }]);
  const quantity = resolved.isMassUnit ? resolved.resolvedQuantity : resolved.lines.reduce((sum, l) => sum + l.quantity, 0);
  const unit = resolved.isMassUnit ? resolved.resolvedUnit : (matItem.purchaseUnit || matItem.unit || null);

  const requestId = await generatePurchaseRequestId();
  try {
    const request = await PurchaseRequest.create({
      requestId,
      productName: matItem.name,
      quantity,
      requestFromDepartment: 'Store',
      priority: 'Medium',
      companyId: matItem.companyId,
      source: 'Store',
      storeApproved: true,
      autoGenerated: true,
      storeOrderId: order._id,
      unit,
      materialCode: compositeMaterialCode,
      itemId: matItem.code,
      fabricationDimensionLines: resolved.lines,
    });
    return request.requestId;
  } catch (err) {
    if (err.code === 11000) {
      const existing = await PurchaseRequest.findOne({
        storeOrderId: order._id, materialCode: compositeMaterialCode, autoGenerated: true,
      }).select('requestId').lean();
      if (existing) return existing.requestId;
    }
    throw err;
  }
}

async function raisePlainPurchaseRequest({ item, shortfallQty, order }) {
  const requestId = await generatePurchaseRequestId();
  try {
    const request = await PurchaseRequest.create({
      requestId,
      productName: item.name,
      quantity: shortfallQty,
      requestFromDepartment: 'Store',
      priority: 'Medium',
      companyId: item.companyId,
      source: 'Store',
      storeApproved: true,
      autoGenerated: true,
      storeOrderId: order._id,
      unit: item.purchaseUnit || item.unit || null,
      materialCode: item.code,
      itemId: item.code,
    });
    return request.requestId;
  } catch (err) {
    if (err.code === 11000) {
      const existing = await PurchaseRequest.findOne({
        storeOrderId: order._id, materialCode: item.code, autoGenerated: true,
      }).select('requestId').lean();
      if (existing) return existing.requestId;
    }
    throw err;
  }
}

// For every In-house Manufactured sale item on this order, checks its BOM's
// raw materials/tools/sheet-metal/length-fabrication against current stock,
// auto-raises a pre-approved Purchase Request for any shortfall, and writes
// the result onto that ONE sale item via a targeted Sale.updateOne — never a
// load-then-save of the whole Sale document (see the model comment on
// Sale.items[].materialAvailability for why: this must be safe to call while
// other requests are concurrently touching the same Sale, in a multi-user
// app). Called (awaited) from orderFormController.js's upsertOrderForm,
// right after the order's Sale document is guaranteed to exist.
export async function computeMaterialAvailabilityForOrder(order) {
  const sale = await Sale.findOne({ order: order._id }).lean();
  if (!sale) return { processed: 0, skipped: 0 };

  const stats = { processed: 0, skipped: 0, errored: 0 };

  for (const saleItem of sale.items || []) {
    if (!saleItem.itemRef) { stats.skipped++; continue; }

    // Independent of saleItem.productType — reads straight off the master
    // Item, so this doesn't have to wait on/depend on Store's own routing
    // classification having already run.
    const machineItem = await Item.findById(saleItem.itemRef);
    if (!machineItem || !machineItem.internalManufacturing) { stats.skipped++; continue; }

    const bom = await RDBOM.findOne({ machine: machineItem._id, company: order.companyId }).lean();
    if (!bom || !bom.materials?.length) { stats.skipped++; continue; }

    // Isolated per sale item — one item's data problem (e.g. a stale
    // dimensionVariantId reference) must never abort every other item's
    // availability check on the same order. Logged and skipped, same
    // "never let one bad row sink the whole request" principle
    // orderFormController.js's own sibling try/catches already follow.
    try {

    const buildQty = Math.max(1, Number(saleItem.quantity) || 1);
    const available = [];
    const needsPurchase = [];

    // ── Tier 1: plain (non-fabrication) raw materials + tools ──────────────
    const plainGroups = plainMaterialGroupsFromBOM(bom);
    for (const g of plainGroups) {
      const code = g.itemCode;
      const matItem = await Item.findOne({ code, companyId: order.companyId });
      if (!matItem) continue;
      const neededQty = g.perUnitQty * buildQty;
      const availableQty = matItem.qty || 0;
      if (availableQty >= neededQty) {
        available.push({ code, name: matItem.name, neededQty, availableQty, unit: matItem.unit });
      } else {
        const shortfallQty = neededQty - availableQty;
        const purchaseRequestId = await raisePlainPurchaseRequest({ item: matItem, shortfallQty, order });
        needsPurchase.push({ code, name: matItem.name, neededQty, availableQty, shortfallQty, unit: matItem.unit, purchaseRequestId });
      }
    }

    // ── Tier 2: Sheet Metal groups (already solved by SheetMetalPlan) ──────
    const sheetGroups = sheetMetalGroupsFromBOM(bom);
    const plans = sheetGroups.length
      ? await SheetMetalPlan.find({ bom: bom._id, company: order.companyId }).lean()
      : [];
    const planByKey = new Map(plans.map(p => [`${p.itemCode}#${p.dimensionVariantId}`, p]));
    for (const g of sheetGroups) {
      const key = `${g.itemCode}#${g.dimensionVariantId}`;
      const plan = planByKey.get(key);
      if (!plan) continue; // unplanned group — lockBOM's gate should prevent this; skip defensively
      const matItem = await Item.findOne({ code: g.itemCode, companyId: order.companyId });
      if (!matItem) continue;
      const variant = (matItem.dimensionVariants || []).find(v => String(v._id) === String(g.dimensionVariantId));
      // A saved dimensionVariantId can go stale if the Item was re-saved
      // since (sanitizeItemData regenerates every variant's _id on every
      // save — see the follow-on doc entry). Skip defensively rather than
      // attempt a purchase request with no real dimension to resolve
      // against — this must never abort the rest of the order's items.
      if (!variant) continue;
      const neededQty = plan.sheetsNeededPerUnit * buildQty;
      const availableQty = variant.subStock || 0;
      if (availableQty >= neededQty) {
        available.push({ code: key, name: g.itemName, neededQty, availableQty, unit: 'Pieces' });
      } else {
        const shortfallQty = neededQty - availableQty;
        const purchaseRequestId = await raiseFabricationPurchaseRequest({
          matItem, dimensionValues: variant.values, piecesShort: Math.ceil(shortfallQty),
          compositeMaterialCode: key, order,
        });
        needsPurchase.push({ code: key, name: g.itemName, neededQty, availableQty, shortfallQty, unit: 'Pieces', purchaseRequestId });
      }
    }

    // ── Tier 3: non-sheet-metal length-based fabrication groups (new) ──────
    const lengthGroups = lengthFabricationGroupsFromBOM(bom);
    for (const g of lengthGroups) {
      const matItem = await Item.findOne({ code: g.itemCode, companyId: order.companyId });
      if (!matItem) continue;
      const variant = (matItem.dimensionVariants || []).find(v => String(v._id) === String(g.dimensionVariantId));
      const catalogPieceLengthMm = Number(variant?.values?.length) || 0;
      if (!variant || !catalogPieceLengthMm) continue;
      const totalLengthNeededMm = g.totalLengthMmPerUnit * buildQty;
      const piecesNeeded = Math.ceil(totalLengthNeededMm / catalogPieceLengthMm);
      const key = `${g.itemCode}#${g.dimensionVariantId}`;
      const availableQty = variant.subStock || 0;
      if (availableQty >= piecesNeeded) {
        available.push({ code: key, name: g.itemName, neededQty: piecesNeeded, availableQty, unit: 'Pieces' });
      } else {
        const shortfallQty = piecesNeeded - availableQty;
        const purchaseRequestId = await raiseFabricationPurchaseRequest({
          matItem, dimensionValues: variant.values, piecesShort: shortfallQty,
          compositeMaterialCode: key, order,
        });
        needsPurchase.push({ code: key, name: g.itemName, neededQty: piecesNeeded, availableQty, shortfallQty, unit: 'Pieces', purchaseRequestId });
      }
    }

    // Single targeted write — see the model comment for why this is never a
    // load-then-save of the whole Sale document.
    await Sale.updateOne(
      { _id: sale._id, 'items._id': saleItem._id },
      { $set: { 'items.$.materialAvailability': { computedAt: new Date(), available, needsPurchase } } }
    );
    stats.processed++;

    } catch (itemErr) {
      console.error(`[MaterialAvailability] Error processing sale item ${saleItem._id}:`, itemErr.message);
      stats.errored++;
    }
  }

  return stats;
}
