import PurchaseRequest from '../models/PurchaseRequest.js';
import { generatePurchaseRequestId } from './storeFlowService.js';
import { resolveFabricationLines } from '../controllers/purchaseRequestController.js';

// Shared, BOM-level-agnostic Purchase Request raisers — used by every tier
// of the new hierarchy's cascade (machineReorderService.js's
// checkMachineAssemblyMaterialAvailability, childPartReorderService.js's
// checkSubChildPartMaterialAvailability, and subChildPartOrderService.js's
// own raw-material check one tier further down). Originally also used by
// this file's own computeMaterialAvailabilityForOrder (the OLD RDBOM-based
// Machine-level shortfall check) — that function and its RDBOM/Sale/
// SheetMetalPlan-only imports were retired 2026-09-16 once
// machineReorderService.js's MachineBOM-based cascade took over its job at
// order-creation time (storeFlowService.js's applyStoreDecisionToItem, CASE
// 2) — full cutover, confirmed with the user: real MachineBOM documents
// already exist (BP816, PRO-0014) and the old RDBOM-based check has no
// remaining caller. RDBOM itself is untouched — still fully intact, visible
// in BOM Management's own "Child Part / Machine BOM (Legacy)" tab.

// Shared by both Sheet Metal and length-based fabrication shortfalls —
// resolveFabricationLines is category-agnostic (just {values, quantity}), so
// the same request-building logic works for either. Pre-approved and
// order-scoped, mirroring lowStockReorderCron.js's own auto-PR shape exactly
// so it displays/behaves identically on the existing (untouched) Material
// Handshake Purchase screens. Relies on PurchaseRequest's new partial unique
// index (storeOrderId + materialCode, autoGenerated) to make a genuine
// duplicate impossible under a concurrent double-submit — on conflict, reuse
// the already-created request's id instead of erroring.
export async function raiseFabricationPurchaseRequest({ matItem, dimensionValues, piecesShort, compositeMaterialCode, order }) {
  const resolved = await resolveFabricationLines(matItem, [{ values: dimensionValues, quantity: piecesShort }]);
  const quantity = resolved.isMassUnit ? resolved.resolvedQuantity : resolved.lines.reduce((sum, l) => sum + l.quantity, 0);
  const unit = resolved.isMassUnit ? resolved.resolvedUnit : (matItem.purchaseUnit || matItem.unit || null);

  const requestId = await generatePurchaseRequestId();
  try {
    const request = await PurchaseRequest.create({
      requestId,
      productName: matItem.name,
      quantity,
      requestFromDepartment: 'Store',
      priority: 'Medium',
      companyId: matItem.companyId,
      source: 'Store',
      storeApproved: true,
      autoGenerated: true,
      storeOrderId: order._id,
      unit,
      materialCode: compositeMaterialCode,
      itemId: matItem.code,
      fabricationDimensionLines: resolved.lines,
    });
    return request.requestId;
  } catch (err) {
    if (err.code === 11000) {
      const existing = await PurchaseRequest.findOne({
        storeOrderId: order._id, materialCode: compositeMaterialCode, autoGenerated: true,
      }).select('requestId').lean();
      if (existing) return existing.requestId;
    }
    throw err;
  }
}

export async function raisePlainPurchaseRequest({ item, shortfallQty, order }) {
  const requestId = await generatePurchaseRequestId();
  try {
    const request = await PurchaseRequest.create({
      requestId,
      productName: item.name,
      quantity: shortfallQty,
      requestFromDepartment: 'Store',
      priority: 'Medium',
      companyId: item.companyId,
      source: 'Store',
      storeApproved: true,
      autoGenerated: true,
      storeOrderId: order._id,
      unit: item.purchaseUnit || item.unit || null,
      materialCode: item.code,
      itemId: item.code,
    });
    return request.requestId;
  } catch (err) {
    if (err.code === 11000) {
      const existing = await PurchaseRequest.findOne({
        storeOrderId: order._id, materialCode: item.code, autoGenerated: true,
      }).select('requestId').lean();
      if (existing) return existing.requestId;
    }
    throw err;
  }
}
