import mongoose from 'mongoose';
import { Item } from '../models/Inventory.js';

// Bakery inventory items with images from Unsplash
const bakeryInventoryItems = [
  {
    name: 'Britannia Good Day Butter Cookies',
    code: 'BGD001',
    category: 'Biscuits',
    subCategory: 'Butter Cookies',
    batch: 'BD240123',
    qty: 150,
    unit: 'Packets',
    store: 'Main Warehouse',
    importance: 'High',
    type: 'Product',
    stdCost: 25.00,
    purchaseCost: 22.50,
    salePrice: 30.00,
    hsn: '19059020',
    gst: 12,
    mrp: 35.00,
    internalManufacturing: false,
    purchase: true,
    description: 'Premium butter cookies with rich taste',
    minStock: 50,
    leadTime: 7,
    customerCategory: 'Retail',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=300&fit=crop'
  },
  {
    name: 'Parle-G Original Biscuits',
    code: 'PG001',
    category: 'Biscuits',
    subCategory: 'Plain',
    batch: 'PG240123',
    qty: 200,
    unit: 'Packets',
    store: 'Main Warehouse',
    importance: 'Critical',
    type: 'Product',
    stdCost: 12.00,
    purchaseCost: 10.50,
    salePrice: 15.00,
    hsn: '19059020',
    gst: 12,
    mrp: 18.00,
    internalManufacturing: false,
    purchase: true,
    description: 'Classic glucose biscuits loved by all',
    minStock: 100,
    leadTime: 5,
    customerCategory: 'Retail',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=300&fit=crop'
  },
  {
    name: 'Oreo Chocolate Cream Cookies',
    code: 'OR001',
    category: 'Cookies',
    subCategory: 'Chocolate Chip',
    batch: 'OR240123',
    qty: 120,
    unit: 'Packets',
    store: 'Main Warehouse',
    importance: 'High',
    type: 'Product',
    stdCost: 35.00,
    purchaseCost: 32.00,
    salePrice: 42.00,
    hsn: '19059020',
    gst: 12,
    mrp: 45.00,
    internalManufacturing: false,
    purchase: true,
    description: 'Chocolate sandwich cookies with cream filling',
    minStock: 40,
    leadTime: 10,
    customerCategory: 'Retail',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=300&fit=crop'
  },
  {
    name: 'Fresh White Bread Loaf',
    code: 'FWB001',
    category: 'Breads',
    subCategory: 'White Bread',
    batch: 'FWB240123',
    qty: 80,
    unit: 'Loaves',
    store: 'Fresh Section',
    importance: 'Critical',
    type: 'Product',
    stdCost: 28.00,
    purchaseCost: 25.00,
    salePrice: 35.00,
    hsn: '19059010',
    gst: 5,
    mrp: 40.00,
    internalManufacturing: true,
    purchase: false,
    description: 'Fresh daily baked white bread',
    minStock: 30,
    leadTime: 1,
    customerCategory: 'Retail',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop'
  },
  {
    name: 'Chocolate Sponge Cake',
    code: 'CSC001',
    category: 'Cakes',
    subCategory: 'Chocolate Cake',
    batch: 'CSC240123',
    qty: 25,
    unit: 'Pieces',
    store: 'Fresh Section',
    importance: 'Normal',
    type: 'Product',
    stdCost: 180.00,
    purchaseCost: 160.00,
    salePrice: 220.00,
    hsn: '19059030',
    gst: 18,
    mrp: 250.00,
    internalManufacturing: true,
    purchase: false,
    description: 'Rich chocolate sponge cake',
    minStock: 10,
    leadTime: 2,
    customerCategory: 'Retail',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop'
  },
  {
    name: 'McVities Digestive Biscuits',
    code: 'MCD001',
    category: 'Biscuits',
    subCategory: 'Digestive',
    batch: 'MCD240123',
    qty: 90,
    unit: 'Packets',
    store: 'Main Warehouse',
    importance: 'High',
    type: 'Product',
    stdCost: 45.00,
    purchaseCost: 42.00,
    salePrice: 52.00,
    hsn: '19059020',
    gst: 12,
    mrp: 58.00,
    internalManufacturing: false,
    purchase: true,
    description: 'Wholesome digestive biscuits',
    minStock: 30,
    leadTime: 8,
    customerCategory: 'Retail',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=300&fit=crop'
  },
  {
    name: 'Burger Buns Pack',
    code: 'BB001',
    category: 'Breads',
    subCategory: 'Burger Buns',
    batch: 'BB240123',
    qty: 60,
    unit: 'Packs',
    store: 'Fresh Section',
    importance: 'Normal',
    type: 'Product',
    stdCost: 32.00,
    purchaseCost: 28.00,
    salePrice: 38.00,
    hsn: '19059010',
    gst: 5,
    mrp: 42.00,
    internalManufacturing: true,
    purchase: false,
    description: 'Soft burger buns - pack of 4',
    minStock: 20,
    leadTime: 1,
    customerCategory: 'Restaurant',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=400&h=300&fit=crop'
  },
  {
    name: 'Sunfeast Dark Fantasy Cookies',
    code: 'SDF001',
    category: 'Cookies',
    subCategory: 'Chocolate Chip',
    batch: 'SDF240123',
    qty: 110,
    unit: 'Packets',
    store: 'Main Warehouse',
    importance: 'High',
    type: 'Product',
    stdCost: 38.00,
    purchaseCost: 35.00,
    salePrice: 45.00,
    hsn: '19059020',
    gst: 12,
    mrp: 50.00,
    internalManufacturing: false,
    purchase: true,
    description: 'Premium dark chocolate cookies',
    minStock: 35,
    leadTime: 7,
    customerCategory: 'Retail',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=300&fit=crop'
  },
  {
    name: 'Fresh Croissants',
    code: 'FC001',
    category: 'Breads',
    subCategory: 'Dinner Rolls',
    batch: 'FC240123',
    qty: 40,
    unit: 'Pieces',
    store: 'Fresh Section',
    importance: 'Normal',
    type: 'Product',
    stdCost: 15.00,
    purchaseCost: 12.00,
    salePrice: 18.00,
    hsn: '19059010',
    gst: 5,
    mrp: 22.00,
    internalManufacturing: true,
    purchase: false,
    description: 'Buttery fresh croissants',
    minStock: 15,
    leadTime: 1,
    customerCategory: 'Retail',
    image: 'https://images.unsplash.com/photo-1555507036-ab794f27d1dc?w=400&h=300&fit=crop'
  },
  {
    name: 'Potato Chips Masala',
    code: 'PCM001',
    category: 'Snacks',
    subCategory: 'Potato Chips',
    batch: 'PCM240123',
    qty: 180,
    unit: 'Packets',
    store: 'Main Warehouse',
    importance: 'High',
    type: 'Product',
    stdCost: 20.00,
    purchaseCost: 18.00,
    salePrice: 25.00,
    hsn: '20052010',
    gst: 12,
    mrp: 30.00,
    internalManufacturing: false,
    purchase: true,
    description: 'Crispy masala flavored potato chips',
    minStock: 60,
    leadTime: 5,
    customerCategory: 'Retail',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&h=300&fit=crop'
  }
];

export const seedBakeryInventory = async () => {
  try {
    console.log('Seeding bakery inventory items...');
    
    // Clear existing items
    await Item.deleteMany({});
    
    // Insert bakery inventory items
    const insertedItems = await Item.insertMany(bakeryInventoryItems);
    console.log(`✓ Inserted ${insertedItems.length} bakery inventory items`);
    
    console.log('Bakery inventory seeded successfully!');
    return insertedItems;
  } catch (error) {
    console.error('Error seeding bakery inventory:', error);
    throw error;
  }
};