import { Item } from '../models/Inventory.js';
import PurchaseRequest from '../models/PurchaseRequest.js';
import { generatePurchaseRequestId } from '../services/storeFlowService.js';
import { resolveFabricationLines } from '../controllers/purchaseRequestController.js';
import { dimensionSignature } from '../services/fabricationDemandService.js';
import notificationService from '../services/notificationService.js';

// Material Flow — Low Stock Auto-Purchase sweep.
//
// Runs periodically (see server/index.js's cron registration) rather than
// hooking into any specific stock-decreasing action, because stock can drop
// through 9+ different places in this codebase (Store's transfer-to-
// production, bulk transfer, fabrication cutting, Store's own QC-routing
// deduction, Dispatch, Sales Invoice, Service-visit parts, Purchase Returns,
// manual stock adjustment) — a single sweep that re-checks every item
// catches all of them uniformly, instead of only whichever ones got an
// explicit hook. Every created request is pre-approved and goes straight to
// Purchase (source: 'Store', storeApproved: true), same as Store's own
// manual "Not Available" requests already work.
const OPEN_STATUSES = ['Pending', 'Approved', 'Ordered'];

async function notifyCreated(request, companyId) {
  try {
    await notificationService.triggerStoreNotification({
      action: 'purchase_request_created',
      data: { requestId: request.requestId, productName: request.productName, priority: request.priority },
      targetCompanyId: companyId,
    });
  } catch (e) {
    console.error('[LowStockReorder] notification error:', e);
  }
}

// Non-fabrication branch: a single flat reorder against the item's own qty.
async function checkPlainItem(item, stats) {
  if (!item.materialFlow || item.qty > item.minStock) return;

  const existing = await PurchaseRequest.exists({
    reorderItemId: item._id,
    autoGenerated: true,
    status: { $in: OPEN_STATUSES },
  });
  if (existing) return;

  const requestId = await generatePurchaseRequestId();
  const request = await PurchaseRequest.create({
    requestId,
    productName: item.name,
    quantity: item.reorderQty,
    requestFromDepartment: 'Store',
    priority: 'Medium',
    companyId: item.companyId,
    source: 'Store',
    storeApproved: true,
    autoGenerated: true,
    reorderItemId: item._id,
    unit: item.purchaseUnit || item.unit || null,
    materialCode: item.code,
  });
  stats.created++;
  await notifyCreated(request, item.companyId);
}

// Fabrication branch: every non-leftover catalog dimensionVariant is its own
// independent flow — dedup matches on fabricationDimensionLines[0].values
// (content-based identity) rather than an ObjectId reference, because
// Item.dimensionVariants[]._id is NOT stable across item edits (see
// PurchaseRequest.js's reorderItemId comment for why).
async function checkFabricationVariants(item, stats) {
  const flagged = (item.dimensionVariants || []).filter(
    (dv) => !dv.isLeftover && dv.materialFlow && (dv.subStock || 0) <= (dv.minStock || 0)
  );
  if (!flagged.length) return;

  const openAutoPRs = await PurchaseRequest.find({
    reorderItemId: item._id,
    autoGenerated: true,
    status: { $in: OPEN_STATUSES },
  }).select('fabricationDimensionLines').lean();
  const openSignatures = new Set(
    openAutoPRs
      .filter((pr) => pr.fabricationDimensionLines?.length === 1)
      .map((pr) => dimensionSignature(pr.fabricationDimensionLines[0].values))
  );

  for (const variant of flagged) {
    const sig = dimensionSignature(variant.values);
    if (openSignatures.has(sig)) continue;

    let resolved;
    try {
      resolved = await resolveFabricationLines(item, [{ values: variant.values, quantity: variant.reorderQty }]);
    } catch (err) {
      console.error(`[LowStockReorder] Skipping ${item.code} dimension ${sig}:`, err.message);
      continue;
    }
    const quantity = resolved.isMassUnit
      ? resolved.resolvedQuantity
      : resolved.lines.reduce((sum, l) => sum + l.quantity, 0);
    const unit = resolved.isMassUnit ? resolved.resolvedUnit : (item.purchaseUnit || item.unit || null);

    const requestId = await generatePurchaseRequestId();
    const request = await PurchaseRequest.create({
      requestId,
      productName: item.name,
      quantity,
      requestFromDepartment: 'Store',
      priority: 'Medium',
      companyId: item.companyId,
      source: 'Store',
      storeApproved: true,
      autoGenerated: true,
      reorderItemId: item._id,
      unit,
      materialCode: item.code,
      fabricationDimensionLines: resolved.lines,
    });
    stats.created++;
    await notifyCreated(request, item.companyId);
  }
}

export async function runLowStockReorderSweep() {
  const stats = { scanned: 0, created: 0 };
  const items = await Item.find({
    isDiscontinued: { $ne: true },
    purchase: true,
    $or: [
      { materialFlow: { $in: ['High Flow', 'Medium Flow', 'Low Flow'] } },
      { 'dimensionVariants.materialFlow': { $in: ['High Flow', 'Medium Flow', 'Low Flow'] } },
    ],
  });

  for (const item of items) {
    stats.scanned++;
    try {
      if (item.fabricationRef) {
        await checkFabricationVariants(item, stats);
      } else {
        await checkPlainItem(item, stats);
      }
    } catch (err) {
      console.error(`[LowStockReorder] Error processing item ${item.code}:`, err);
    }
  }

  console.log(`[LowStockReorder] Sweep complete — scanned ${stats.scanned} item(s), created ${stats.created} purchase request(s).`);
  return stats;
}
