import mongoose from 'mongoose';

const purchaseRequestSchema = new mongoose.Schema({
  requestId: {
    type: String,
    required: true,
    unique: true
  },
  productName: {
    type: String,
    required: true
  },
  quantity: {
    type: Number,
    required: true
  },
  requestFromDepartment: {
    type: String,
    required: true,
    enum: ['Store', 'Production', 'QC', 'Sales', 'Other'],
    default: 'Store'
  },
  requestDate: {
    type: Date,
    default: Date.now
  },
  priority: {
    type: String,
    enum: ['Low', 'Medium', 'High'],
    default: 'Medium'
  },
  status: {
    type: String,
    enum: ['Pending', 'Approved', 'Ordered', 'Received', 'Rejected'],
    default: 'Pending'
  },
  companyId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Company',
    required: true
  },
  storeOrderId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Order'
  },
  itemId: {
    type: String
  },
  // Which specific Sale item (Sale.items._id) this request purchases —
  // multi-item orders raise one Purchase Request per item. Null on legacy.
  saleItemId: {
    type: mongoose.Schema.Types.ObjectId,
    default: null
  },
  purchaseOrder: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Purchase'
  },
  // Fields required at the time of marking as Received
  serialNumber: {
    type: String,
    trim: true,
    default: null
  },
  warrantyPeriod: {
    type: Number,   // in months
    default: null
  },
  warrantyCardUrl: {
    type: String,
    trim: true,
    default: null
  },
  receivedAt: {
    type: Date,
    default: null
  },
  // Source of the purchase request
  source: {
    type: String,
    enum: ['Store', 'Production', 'QC'],
    default: 'Store'
  },
  // Whether Store has approved a Production-sourced request to go to Purchase dept
  storeApproved: {
    type: Boolean,
    default: false
  },
  storeApprovedAt: {
    type: Date,
    default: null
  },
  // Set only by the low-stock auto-purchase sweep (see
  // server/jobs/lowStockReorderCron.js) — distinguishes a system-raised
  // request from one a person clicked. reorderItemId is what the sweep's own
  // dedup check queries by, so it never raises a second open request for the
  // same still-low item on its next tick. For a fabrication dimension,
  // there's deliberately no ObjectId reference to the specific
  // dimensionVariants[] entry — Item.dimensionVariants[]._id is NOT stable
  // across item edits (sanitizeItemData's dimensionVariants map rebuilds
  // plain objects without carrying over _id, so Mongoose mints fresh ones on
  // every save) — so dedup instead matches on fabricationDimensionLines[0]
  // .values, the same content-based identity fabricationDimensionLines
  // already uses everywhere else in this file.
  autoGenerated: { type: Boolean, default: false },
  reorderItemId: { type: mongoose.Schema.Types.ObjectId, ref: 'Item', default: null },
  // Production material demand details
  unit: {
    type: String,
    default: null
  },
  materialCode: {
    type: String,
    default: null
  },
  // Fabrication Master items only — Store can request several catalog
  // dimensionVariants of the same item in one consolidated request (e.g.
  // 20kg worth of one sheet size + 10kg of another). Each line's values must
  // match an existing catalog dimensionVariant — never a leftover variant,
  // see Item.dimensionVariants[].isLeftover. Purchase edits this same array
  // (adding/removing/adjusting lines) from the "Send RFQ" form before the
  // request goes out — see rfqController.js's createRFQ. Empty array for
  // every non-fabrication request. The vendor never sees these as separate
  // line items — only the aggregate top-level quantity/unit (below) is what's
  // actually negotiated/billed; these are read-only breakdown context.
  fabricationDimensionLines: {
    type: [{
      values: { type: mongoose.Schema.Types.Mixed, required: true },
      quantity: { type: Number, required: true, min: 1 },
      weightPerPieceKg: { type: Number, default: null },
      lineWeightKg: { type: Number, default: null },
    }],
    default: []
  },
  // Fabrication Master items only — what Store actually recorded at receive
  // time (server/controllers/purchaseRequestController.js's
  // receiveFabricationPurchase), same shape as fabricationDimensionLines
  // above but may differ from it — the vendor can ship a different size mix
  // than what was ordered/quoted, including a dimension not in the item's
  // catalog at all (see Item.dimensionVariants[].isLeftover — an off-catalog
  // receipt is credited as stock but flagged isLeftover, same as a Store-cut
  // leftover). fabricationDimensionLines stays untouched as "what was
  // ordered"; this is "what was received." Empty for every non-fabrication
  // request and for a fabrication request not yet received.
  receivedFabricationLines: {
    type: [{
      values: { type: mongoose.Schema.Types.Mixed, required: true },
      quantity: { type: Number, required: true, min: 1 },
      weightPerPieceKg: { type: Number, default: null },
      lineWeightKg: { type: Number, default: null },
    }],
    default: []
  },
  // ── Unit-conversion purchase flow (items with a defined Purchase Unit) ──
  purchaseUnitType: {
    type: String,
    default: null
  },
  purchaseUnit: {
    type: String,   // unit the Purchase dept ordered in (e.g. Kilogram)
    default: null
  },
  purchaseQuantity: {
    type: Number,   // qty ordered in purchaseUnit (entered at Send RFQ)
    default: null
  },
  receivedQuantity: {
    type: Number,   // qty received in purchaseUnit (entered by Store at receive)
    default: null
  },
  conversionFactor: {
    type: Number,   // how many purchaseUnit make 1 base unit (e.g. 1 pc = 1 kg)
    default: null
  },
  convertedQuantity: {
    type: Number,   // base-unit qty sent to QC / inventory
    default: null
  },
  // Rejection details
  rejectedAt: {
    type: Date,
    default: null
  },
  rejectionReason: {
    type: String,
    default: null
  }
}, { timestamps: true });

// Dedup guard for materialAvailabilityService.js's order-scoped auto-raised
// requests — one request per (order, material) even under a genuine
// concurrent double-submit (relying on a check-then-create query alone
// isn't race-proof; this makes a duplicate impossible at the DB level).
// Scoped with storeOrderId: {$exists:true} in the partial filter so this
// does NOT constrain lowStockReorderCron.js's own auto-generated requests —
// those are Item-scoped (reorderItemId), never set storeOrderId, and a
// fabrication item can legitimately have several of them sharing the same
// materialCode (one per flagged dimension variant) — this index must not
// collide with that existing, unrelated dedup scheme.
purchaseRequestSchema.index(
  { storeOrderId: 1, materialCode: 1 },
  { unique: true, partialFilterExpression: { autoGenerated: true, storeOrderId: { $exists: true } } }
);

export default mongoose.model('PurchaseRequest', purchaseRequestSchema);
